import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:sadhana_cart/core/common%20model/product/product_model.dart';

final List<ProductModel> productModel = [
  // 1. Ultrabook
  ProductModel(
    productId: 'LAP001',
    name: 'UltraBook Pro 14',
    description: 'Premium lightweight laptop for professionals',
    category: 'laptop',
    subcategory: 'ultrabook',
    sku: 'LAP-UBP-SLV-I7',
    brand: 'TechElite',
    price: 1499.99,
    offerPrice: 1299.99,
    stock: 25,
    rating: 4.8,
    timestamp: Timestamp.now(),
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853',
    ],
    sellerId: 'seller123',
    cashOnDelivery: "Yes",
    model: 'UltraBook Pro 14',
    graphics: 'Intel Iris Xe',
    ram: '16GB',
    storage: '512GB SSD',
    battery: 'Up to 12 hours',
    camera: '1080p HD',
    processor: 'Intel Core i7-1260P',
    display: '14-inch 2.8K OLED',
    os: 'Windows 11 Pro',
    connectivity: 'Thunderbolt 4, Wi-Fi 6E, Bluetooth 5.2',
    warranty: '2 Years',
    screenSize: ['14 inches'],
    operatingSystem: 'Windows 11 Pro',
    port: '2x Thunderbolt 4, 1x USB-C, 1x HDMI',
    weight: '2.8 lbs',
  ),

  // 2. Gaming Laptop
  ProductModel(
    productId: 'LAP002',
    name: 'GameForce 15',
    description: 'High-performance gaming laptop with dedicated graphics',
    category: 'laptop',
    subcategory: 'gaming',
    sku: 'LAP-GMF-BLK-RTX',
    brand: 'GameTech',
    price: 1699.99,
    offerPrice: 1499.99,
    stock: 20,
    rating: 4.7,
    timestamp: Timestamp.now(),
    images: [
      'https://images.unsplash.com/photo-1593640408182-31c70c8268f5',
      'https://images.unsplash.com/photo-1593640408182-31c70c8268f5',
    ],
    sellerId: 'seller456',
    cashOnDelivery: "Yes",
    model: 'GameForce 15',
    graphics: 'NVIDIA RTX 4060 8GB',
    ram: '32GB',
    storage: '1TB SSD',
    battery: 'Up to 6 hours',
    camera: '720p HD',
    processor: 'Intel Core i7-13700H',
    display: '15.6-inch QHD 165Hz',
    os: 'Windows 11 Home',
    connectivity: 'Wi-Fi 6, Bluetooth 5.1, Ethernet',
    warranty: '2 Years',
    screenSize: ['15.6 inches'],
    operatingSystem: 'Windows 11 Home',
    port: '1x Thunderbolt 4, 3x USB-A, 1x HDMI, 1x Ethernet',
    weight: '5.1 lbs',
  ),

  // 3. Budget Laptop
  ProductModel(
    productId: 'LAP003',
    name: 'Everyday Value 15',
    description: 'Affordable laptop for everyday tasks',
    category: 'laptop',
    subcategory: 'budget',
    sku: 'LAP-EDV-GRY-I5',
    brand: 'ValueComputing',
    price: 599.99,
    offerPrice: 499.99,
    stock: 50,
    rating: 4.3,
    timestamp: Timestamp.now(),
    images: [
      'https://images.unsplash.com/photo-1587614382346-4ec70e388b28',
      'https://images.unsplash.com/photo-1587614382346-4ec70e388b28',
    ],
    sellerId: 'seller789',
    cashOnDelivery: "Yes",
    model: 'Everyday Value 15',
    graphics: 'Intel UHD Graphics',
    ram: '8GB',
    storage: '256GB SSD',
    battery: 'Up to 8 hours',
    camera: '720p HD',
    processor: 'Intel Core i5-1235U',
    display: '15.6-inch FHD IPS',
    os: 'Windows 11 Home',
    connectivity: 'Wi-Fi 5, Bluetooth 4.2',
    warranty: '1 Year',
    screenSize: ['15.6 inches'],
    operatingSystem: 'Windows 11 Home',
    port: '2x USB-A, 1x USB-C, 1x HDMI',
    weight: '3.7 lbs',
  ),

  // 4. 2-in-1 Convertible
  ProductModel(
    productId: 'LAP004',
    name: 'FlexConvert 13',
    description: 'Versatile 2-in-1 laptop with touchscreen',
    category: 'laptop',
    subcategory: '2-in-1',
    sku: 'LAP-FLC-BLU-I7',
    brand: 'VersaTech',
    price: 1199.99,
    offerPrice: 999.99,
    stock: 35,
    rating: 4.6,
    timestamp: Timestamp.now(),
    images: [
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef',
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef',
    ],
    sellerId: 'seller101',
    cashOnDelivery: "Yes",
    model: 'FlexConvert 13',
    graphics: 'Intel Iris Xe',
    ram: '16GB',
    storage: '512GB SSD',
    battery: 'Up to 10 hours',
    camera: '1080p HD',
    processor: 'Intel Core i7-1250U',
    display: '13.4-inch FHD Touch',
    os: 'Windows 11 Home',
    connectivity: 'Wi-Fi 6, Bluetooth 5.1',
    warranty: '2 Years',
    screenSize: ['13.4 inches'],
    operatingSystem: 'Windows 11 Home',
    port: '2x Thunderbolt 4, 1x USB-A',
    weight: '2.9 lbs',
  ),

  ProductModel(
    productId: "LAP005",
    name: "Nike Air Max 90",
    description:
        "The Nike Air Max 90 is a classic running shoe that is now a lifestyle icon. With its visible Air unit and comfortable fit, it's no wonder it's been a favorite among sneakerheads and casual wearers alike.",
    category: "Footwear",
    subcategory: "shoe",
    sku: "dummy sku",
    brand: "Nike",
    price: 2000,
    offerPrice: 500,
    stock: 10,
    rating: 4.6,
    timestamp: Timestamp.now(),
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=698&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],

    cashOnDelivery: "Yes",
    footwearSize: ["6", "7", "8", "9", "10"],
    footwearColor: [
      "Red",
      "Blue",
      "Green",
      "Black",
      "White",
      "Yellow",
      "Orange",
    ],
    footwearMaterial: "Leather",
    footwearType: "Sneaker",
    gender: "Male",
  ),
];
