import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:sadhana_cart/core/common%20model/product/product_model.dart';

final List<ProductModel> productModel = [
  ProductModel(
    productId: 'prod_001',
    name: 'Classic Cotton T-Shirt',
    description:
        'A comfortable and breathable cotton T-shirt for everyday use. Made with 100% cotton and perfect for casual wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    sku: 'TSHIRT-CC-001',
    brand: 'CottonWear',
    price: 19.99,
    offerPrice: 14.99,
    stock: 150,
    rating: 4.5,
    timestamp: Timestamp.now(),
    images: [
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
    ],
    cashOnDelivery: "Yes",
    attributes: {
      'Size': 'M',
      'Color': 'Navy Blue',
      'Material': '100% Cotton',
      'Fit': 'Regular',
      'Pattern': 'Solid',
      'Sleeve Type': 'Short Sleeve',
      'Care Instruction': 'Machine wash',
    },
  ),
  ProductModel(
    productId: 'prod_002',
    name: 'Slim Fit Cotton T-Shirt',
    description:
        'A slim fit cotton T-shirt for everyday use. Made with 100% cotton and perfect for casual wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    sku: 'TSHIRT-SF-002',
    brand: 'CottonWear',
    price: 24.99,
    offerPrice: 19.99,
    stock: 120,
    rating: 4.8,
    timestamp: Timestamp.now(),
    images: [
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
    ],
    cashOnDelivery: "Yes",
    attributes: {
      'Size': 'L',
      'Color': 'Light Blue',
      'Material': '100% Cotton',
      'Fit': 'Slim',
      'Pattern': 'Solid',
      'Sleeve Type': 'Short Sleeve',
      'Care Instruction': 'Machine wash',
    },
  ),
  ProductModel(
    productId: 'prod_003',
    name: 'Crew Neck Cotton T-Shirt',
    description:
        'A crew neck cotton T-shirt for everyday use. Made with 100% cotton and perfect for casual wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    sku: 'TSHIRT-CN-003',
    brand: 'CottonWear',
    price: 22.99,
    offerPrice: 17.99,
    stock: 100,
    rating: 4.2,
    timestamp: Timestamp.now(),
    images: [
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
    ],
    cashOnDelivery: "Yes",
    attributes: {
      'Size': 'XL',
      'Color': 'Dark Grey',
      'Material': '100% Cotton',
      'Fit': 'Regular',
      'Pattern': 'Solid',
      'Sleeve Type': 'Short Sleeve',
      'Care Instruction': 'Machine wash',
    },
  ),
  ProductModel(
    productId: 'prod_004',
    name: 'V Neck Cotton T-Shirt',
    description:
        'A V neck cotton T-shirt for everyday use. Made with 100% cotton and perfect for casual wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    sku: 'TSHIRT-VN-004',
    brand: 'CottonWear',
    price: 21.99,
    offerPrice: 16.99,
    stock: 80,
    rating: 4.0,
    timestamp: Timestamp.now(),
    images: [
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
    ],
    cashOnDelivery: "Yes",
    attributes: {
      'Size': 'S',
      'Color': 'White',
      'Material': '100% Cotton',
      'Fit': 'Regular',
      'Pattern': 'Solid',
      'Sleeve Type': 'Short Sleeve',
      'Care Instruction': 'Machine wash',
    },
  ),
  ProductModel(
    productId: 'prod_005',
    name: 'Oversized Cotton T-Shirt',
    description:
        'An oversized cotton T-shirt for everyday use. Made with 100% cotton and perfect for casual wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    sku: 'TSHIRT-OS-005',
    brand: 'CottonWear',
    price: 29.99,
    offerPrice: 24.99,
    stock: 60,
    rating: 4.6,
    timestamp: Timestamp.now(),
    images: [
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
    ],
    cashOnDelivery: "Yes",
    attributes: {
      'Size': 'XXL',
      'Color': 'Black',
      'Material': '100% Cotton',
      'Fit': 'Oversized',
      'Pattern': 'Solid',
      'Sleeve Type': 'Short Sleeve',
      'Care Instruction': 'Machine wash',
    },
  ),
  ProductModel(
    productId: 'prod_006',
    name: 'Polo Cotton T-Shirt',
    description:
        'A polo cotton T-shirt for everyday use. Made with 100% cotton and perfect for casual wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    sku: 'TSHIRT-PL-006',
    brand: 'CottonWear',
    price: 25.99,
    offerPrice: 19.99,
    stock: 40,
    rating: 4.4,
    timestamp: Timestamp.now(),
    images: [
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
    ],
    cashOnDelivery: "Yes",
    attributes: {
      'Size': 'M',
      'Color': 'Red',
      'Material': '100% Cotton',
      'Fit': 'Regular',
      'Pattern': 'Solid',
      'Sleeve Type': 'Short Sleeve',
      'Care Instruction': 'Machine wash',
    },
  ),
  ProductModel(
    productId: 'prod_007',
    name: 'Golf Cotton T-Shirt',
    description:
        'A golf cotton T-shirt for everyday use. Made with 100% cotton and perfect for casual wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    sku: 'TSHIRT-GF-007',
    brand: 'CottonWear',
    price: 23.99,
    offerPrice: 18.99,
    stock: 20,
    rating: 4.1,
    timestamp: Timestamp.now(),
    images: [
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
    ],
    cashOnDelivery: "Yes",
    attributes: {
      'Size': 'L',
      'Color': 'Navy Blue',
      'Material': '100% Cotton',
      'Fit': 'Regular',
      'Pattern': 'Solid',
      'Sleeve Type': 'Short Sleeve',
      'Care Instruction': 'Machine wash',
    },
  ),
  ProductModel(
    productId: 'prod_008',
    name: 'Henley Cotton T-Shirt',
    description:
        'A Henley cotton T-shirt for everyday use. Made with 100% cotton and perfect for casual wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    sku: 'TSHIRT-HL-008',
    brand: 'CottonWear',
    price: 22.99,
    offerPrice: 17.99,
    stock: 10,
    rating: 4.3,
    timestamp: Timestamp.now(),
    images: [
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
    ],
    cashOnDelivery: "Yes",
    attributes: {
      'Size': 'XL',
      'Color': 'Grey',
      'Material': '100% Cotton',
      'Fit': 'Regular',
      'Pattern': 'Solid',
      'Sleeve Type': 'Short Sleeve',
      'Care Instruction': 'Machine wash',
    },
  ),
  ProductModel(
    productId: 'prod_009',
    name: 'Crew Neck Cotton T-Shirt',
    description:
        'A crew neck cotton T-shirt for everyday use. Made with 100% cotton and perfect for casual wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    sku: 'TSHIRT-CN-009',
    brand: 'CottonWear',
    price: 21.99,
    offerPrice: 16.99,
    stock: 50,
    rating: 4.0,
    timestamp: Timestamp.now(),
    images: [
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
      'https://m.media-amazon.com/images/I/41W-l4gvACL.jpg',
    ],
    cashOnDelivery: "Yes",
    attributes: {
      'Size': 'S',
      'Color': 'White',
      'Material': '100% Cotton',
      'Fit': 'Regular',
      'Pattern': 'Solid',
      'Sleeve Type': 'Short Sleeve',
      'Care Instruction': 'Machine wash',
    },
  ),
];
