import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:sadhana_cart/core/common%20model/product/product_model.dart';
import 'package:sadhana_cart/core/common%20model/product/size_variant.dart';

final List<ProductModel> sampleProducts = [
  ProductModel(
    productId: 'P001',
    name: 'Cotton T-Shirt',
    description: 'Comfortable cotton t-shirt for everyday wear.',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    baseSku: 'TSHIRT001',
    brand: 'ComfortWear',
    price: 499.0,
    offerPrice: 399.0,
    rating: 4.5,
    timestamp: Timestamp.now(),
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sellerId: 'SELLER001',
    cashOnDelivery: true,
    colorOptions: ['Red', 'Blue', 'Black'],
    material: 'Cotton',
    fit: 'Regular',
    pattern: 'Solid',
    sleeveType: 'Short Sleeve',
    careInstruction: 'Machine Wash',
    sizeOptions: ['S', 'M', 'L', 'XL'],
    sizeVariants: [
      SizeVariant(size: 'S', stock: 10),
      SizeVariant(size: 'M', stock: 15),
      SizeVariant(size: 'L', stock: 5),
    ],
  ),
  ProductModel(
    productId: 'P002',
    name: 'Denim Jeans',
    description: 'Stylish and durable denim jeans.',
    category: 'Clothing',
    subcategory: 'Jeans',
    baseSku: 'JEANS001',
    brand: 'UrbanStyle',
    price: 1299.0,
    offerPrice: 1099.0,
    rating: 4.2,
    timestamp: Timestamp.now(),
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sellerId: 'SELLER002',
    cashOnDelivery: true,
    colorOptions: ['Blue', 'Black'],
    material: 'Denim',
    fit: 'Slim',
    pattern: 'Faded',
    sleeveType: null,
    careInstruction: 'Wash Inside Out',
    sizeOptions: ['30', '32', '34', '36'],
    sizeVariants: [
      SizeVariant(size: '30', stock: 8),
      SizeVariant(size: '32', stock: 12),
    ],
  ),
  ProductModel(
    productId: 'P003',
    name: 'Running Shoes',
    description: 'Lightweight running shoes for everyday fitness.',
    category: 'Footwear',
    subcategory: 'Sports Shoes',
    baseSku: 'SHOES001',
    brand: 'FitRun',
    price: 1999.0,
    offerPrice: 1799.0,
    rating: 4.8,
    timestamp: Timestamp.now(),
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sellerId: 'SELLER003',
    cashOnDelivery: false,
    colorOptions: ['Grey', 'White'],
    material: 'Mesh',
    fit: null,
    pattern: 'Textured',
    sleeveType: null,
    careInstruction: 'Hand Wash',
    sizeOptions: ['7', '8', '9', '10'],
    sizeVariants: [
      SizeVariant(size: '8', stock: 20),
      SizeVariant(size: '9', stock: 18),
    ],
  ),
  ProductModel(
    productId: 'P004',
    name: 'Woolen Sweater',
    description: 'Warm and cozy woolen sweater for winter.',
    category: 'Clothing',
    subcategory: 'Sweaters',
    baseSku: 'SWTR001',
    brand: 'WinterWear',
    price: 1499.0,
    offerPrice: 1299.0,
    rating: 4.3,
    timestamp: Timestamp.now(),
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sellerId: 'SELLER004',
    cashOnDelivery: true,
    colorOptions: ['Grey', 'Maroon'],
    material: 'Wool',
    fit: 'Slim',
    pattern: 'Knitted',
    sleeveType: 'Full Sleeve',
    careInstruction: 'Dry Clean Only',
    sizeOptions: ['M', 'L', 'XL'],
    sizeVariants: [
      SizeVariant(size: 'M', stock: 7),
      SizeVariant(size: 'L', stock: 10),
    ],
  ),
  ProductModel(
    productId: 'P005',
    name: 'Leather Wallet',
    description: 'Premium quality leather wallet for men.',
    category: 'Accessories',
    subcategory: 'Wallets',
    baseSku: 'WALLET001',
    brand: 'EliteLeather',
    price: 899.0,
    offerPrice: 799.0,
    rating: 4.6,
    timestamp: Timestamp.now(),
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sellerId: 'SELLER005',
    cashOnDelivery: true,
    colorOptions: ['Brown', 'Black'],
    material: 'Leather',
    fit: null,
    pattern: 'Solid',
    sleeveType: null,
    careInstruction: 'Wipe with clean cloth',
    sizeOptions: null,
    sizeVariants: [],
  ),
];
